### ISSUE TITLE
Altinn Dødsbo Dashboard

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#104]
#### Brukerhistorie:
Som en arving
ønsker jeg å se en oversikt over skifteprosessen 
slik at jeg kan forstå hvordan jeg skal gjennomføre et skifte.

#### Forretningsverdi 1 - Kritisk

Lenke til trådskisser:
Lenke til design: https://www.figma.com/proto/yO6LtMoTol4UCNneZcAtbu/Designskisser?node-id=1%3A2&viewport=17%2C-44%2C0.8152644038200378&scaling=scale-down

Lenke til arkitektur:

Godkjent Juridisk (OK // N/A // Ikke godkjent)
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- bruker skal se en landingsside....
- bruker skal se siste aktivitet på boet
- ha mulighet til å se videre informasjon om boet (blant annet om testamentet og ektepakt)
- ha mulighet til å se videre oversikt over formue og gjeld
- valg av skifteform

#### Forbehold for å få realisere denne brukerhistorien:
- [ ] I første omgang kan dette være statisk informasjon, der de ulike komponentene kan oppdateres i separate brukerhistorier 
- [ ] Rettslig grunnlag for at bruker skal få logge inn og vi kan vise personopplysninger om arvingen
- [ ] Avklart hva appen vår skal hete

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by lillelars** [comment]
@kajabystol Hva kaller vi den første siden arving kommer til etter pålogging?
Kan denne begynnes med for trådskissenivå?

**Comment by lillelars** [comment]
@JanAage99 setter denne til en epic og deler den opp i flere brukerhistorier, ettersom den blir veldig stor å realisere. Hva tenker du om det?

**Comment by TageGitHub** [comment]
Videreført i bh #121 Brukere skal se landingsside...
