### ISSUE TITLE
Bruker logger på Altinn dødsbo

### ISSUE THREAD

**Issue by lillelars** [Altinn/oed#15]
#### Brukerhistorie
**Intro**
Som en .... 
ønsker jeg å ....
slik at jeg ... f

**Krav/akseptansekriterier**  _(detaljering av BH med tilhørende akseptansekriterier)_
Gitt at.. jeg har logget inn i Altinn Dødsbo
så... skal jeg se en komponent som heter "rett til arv i boet"
og... Den skal inneholde informasjon om meg som arving, ved mitt navn og min relasjon til avdøde
og... den skal inneholde informasjon om det er registret et testamentet eller ikke
og... 

Gitt at.. jeg har logget inn i Altinn Dødsbo
når...jeg klikker på lenken "andre arvinger" 
så... skal jeg bli tatt til en side som gir mer informasjon om arvingene

Gitt at.. jeg har logget inn i Altinn Dødsbo
når...jeg klikker på lenken "testamente" 
så... skal jeg bli tatt til en side som gir mer informasjon om testamente

Gitt at.. jeg har logget inn i Altinn Dødsbo
når...jeg klikker på lenken "Dine rettigheter" 
så... skal jeg bli tatt til en side som gir mer informasjon om mine rettigheter

**Utfyllende tekst**
  - Alle lenkene skal være selvforklarende slik at bruker forstår hva den gjør (en tekst som forteller bruker hva inngangen gjør)
  - Uavhengig av scenariet skal alle arvinger se denne inngangen.
 -  Denne bh omhandler ikke populering av skjermbilde med reelle data.
 - Skjermbilde skal utformes  iht. vedlagt design

### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): ok
Avklaringsområder: 
 - (aktiva/passiva = formue/gjeld? i tilfelle beslutt begrep) - Besluttet bruk av Formue/gjeld i skjermbilde ettersom dette er mer brukernært begrep.
 - kun skjermbilde, bruk av datakilder i senere BH?) - Ja vi viser bare inngangen til skjermbilde 
 - Uavhengig av scenariet skal alle arvinger se denne inngangen.

**Dokumentasjon**

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: https://eggedosis.github.io/oed/redirects/design/dashboard/concept-3.html

**Teknisk**
Status(ok, under avklaring, n/a): ?
Avklaringsområder:
Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): ?
Avklaringsområder:
Dokumentasjon:

### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): må
Teknisk modenhet (høy, medium, lav): høy
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): n/a

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier:
 - vurder og skisser om bruker skal kunne se en indikasjon på fremgang i prosess (f.eks en progresjonsbar) => Vurderes ikke som kritisk for løsningen. tas ev. opp på nytt dersom brukerbehovet blir tydeligere (tage).
 - Populering av skjermbilder med reelle data.

---
### Åpne punkter - lukkes før sprint

---
### Annet

---
### Scenario X _Opprettes før lukking av denne BH_

**Forslag nye brukerhistorier Scenario X (MVP)**  
 - pålogging av bruker mot Altinn Autorisasjon 

**Avklaringer scenario X**

---
---

#### Brukerhistorie:
Som en arving
ønsker jeg logge inn på Altinn dødsbo 
slik at jeg kan starte skifteprosess

#### Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):
1. Kritisk

Lenke til trådskisser:
Lenke til design:
Lenke til arkitektur:

#### TODO for å realisere denne brukerhistorien:
- Kart over roller og rettigheter må utarbeides

#### Akseptansekriterier (minimum happy-case):

- [ ] Arving skal få tilgang til tjeneste via Altinn sin meldingsinnboks

- [ ] Arving skal kunne logge inn ved å benytte ID-porten

- [ ] Arving skal etter å ha logget seg inn, fått tildelt rolle og komme til landingsside/dashboard for Altinn Dødsbo

#### Avklaringer for å få realisere denne brukerhistorien:
- [ ] at vi har rettslig grunnlag for å behandle navn/fødselsnr i en påloggingsprosess

- [ ] Beskrivelse av de ulike roller og rettigheter for scenarie 1 må på plass

- [ ] Hvor ligger tjenesten, altså hvor skal bruker logges seg inn?  Se #132 

- [ ] Hva skal tjenesten hete? Se #20 

#### Annen informasjon om dette behovet:

- [ ] For vår del (OED) er det nesten ingenting å gjøre av implementasjon her. Det meste ligger hos AltinnAutorisasjon. Vi må teste og verifisere at bruker får logget seg på og får tildelt korrekt rolle. 
Pr i dag er rolletildelingen som gjøres i T3.0 enkel: Man kan bare spesifisere hvilke roller som skal ha tilgang til å bruke en gitt app. Dette er definert i app.config for app. Dvs at bruker må være medlem av rolle definert i app.config for å logge seg på og ta app i bruk. Denne funksjonaliteten i T3.0 vil raffineres og utvides etterhvert. 

#### SCENERAIO X Akseptansekriterier (minimum happy-case):

- [ ] Bruker skal få tilgang til tjeneste fra et annet sted enn Altinn innbox?

#### Scenario:
Bruker skal se startbilde for Altinn dødsbo
gitt at bruker har logget seg inn
så skal startbilde for Altinn dødsbo vises.

**Comment by TageGitHub** [comment]
Videreført i #148
