### ISSUE TITLE
Bruk av formuesfullmakt

### ISSUE THREAD

**Issue by TageGitHub** [Altinn/oed#212]
**Epos** 
Informasjon fra aktør hentes ved at Altinn dødsbo sender et token til aktørens system og aktøren autentiserer Altinn dødsbo ved bruk av dette.

**Krav/akseptansekriterier** 
Gitt at et token er utstedt av Maskinporten basert på Altinn sertifikat
Når Altinn dødsbo skal hente informasjon  fra aktøren
så skal tokenet sendes aktør sammen med avdødes fødselsnummer
og
informasjon som mottas skal lagres på bo-instansen

Gitt at en arving er godkjent i rollen 'arving_med_fulle_rettigheter'
Når denne arvingen er logget på 
så skal denne kunne se informasjon om avdødes formue/gjeld.

**Utfyllende tekst**

##### Oppgaver:

- [ ] Presentere forslaget ut til aktørene og få GO/NO-GO for å benytte dette @TageGitHub @lillelars (må gjøres etter juridiske vurderinger er ferdig)

---
### Utfyllende informasjon
**Funksjonelt**
Status (ok, under avklaring, n/a): 
Avklaringsområder: 
- [x] Skal andre arvinger enn de med rollen 'fulle rettigheter' kunne se informasjon om avdødes gjelde og formue? @tblix 
Dokumentasjon
- [ ] Avklar med Domstolene  hva som er grunnlaget for generering av formuesfullmakt, og om dette kan automatiseres i Altinn dødsbo.

Prosess
https://teams.microsoft.com/l/file/2AFFF01D-32DF-4F38-9D98-15C399977892?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=pptx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall%2FDelte%20dokumenter%2FGeneral%2FRealiseringsfasen%2FFunksjonelt%2FProsess%20Applikasjon%20Dataflyt%2FEpos%20213%20Formuesfullmakt.pptx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_DSOPOppgjretterddsfall&serviceName=teams&threadId=19:3d13bc45f93147f0b8f98e48eae64227@thread.skype&groupId=2215cbdb-4e72-48c6-9c37-e73d84001515

**GUI**
Status: (ok, under avklaring, n/a):
Avklaringsområder:
Dokumentasjon: 

**Teknisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:

- [x] Opprette flyt på hvordan autorisering m/ maskinporten fungerer for at OED skal kunne innhente informasjon fra aktørene på vegne av arving/arvinger @HenningNormann 

Teknisk har kommet opp med løsningsforslag. Se her:
https://teams.microsoft.com/l/file/F7EF3C8B-550D-4EA1-94B3-409ABC49EA06?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_Digdir-Domstolsadministrasjonen%2FDelte%20dokumenter%2FGeneral%2FPresentasjoner%2FForslag%20til%20autorisasjon%20av%20aksess%20til%20eksterne%20systemer.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FProsjekt_Digdir-Domstolsadministrasjonen&serviceName=teams&threadId=19:30aadf5e99f54609a60534084bd7ccda@thread.tacv2&groupId=7e4f0eab-d183-4a11-b13f-aebafeb14ac6

Dokumentasjon:

**Juridisk**
Status(ok, under avklaring, n/a): 
Avklaringsområder:
- [ ] Gjennomgå forslaget til Henning - vurdere tiltak AA og OED må evnt gjøre for å kunne benytte dette forslaget @lillelars  @tblix @benedicteos @HenningNormann 
- [ ] Alt1. Forutsetter dette er maskinporten som autentisering/autorisasjonen (scope)?
- [ ] Alt2. Autentisering på personnivå?
- [ ] Kan vi klare oss med autorisasjon på AltInn dødsbo siden.
- [ ] Beskrive hvordan formuesfullmakt kan håndteres  via maskinporten. Henning ->
- [ ] Tolkning av loven as is: Må arving aktivt KREVE dette fra DA, eller kan vi f.eks få dette via saksAPI'et tidlig i prosessen, f.eks ved opprettelse av bo?
- Hva skjer da med arvinger under 1G? (Kan vi f.eks se bort fra dette i MVP / begrense scopet?)
- [ ] Hva gjør vi med testamentsarvinger når det kommer til etablering/kreving av formuesfullmakt?
- [ ] Hvilke rammebetingelser gjelder for å generere/utstede formuesfullmakt?
- [ ] Kan formuesfullmakt automatisk utstedes fra Altinn dødsbo?
- [ ] Vil maskinporten kunne autorisere på vegne av en arving?

Dokumentasjon:

---
### Prioriteringskriterier produktkø
Funksjonell viktighet (må, bør, vent): 
Teknisk modenhet (høy, medium, lav): 
Samarbeidspartnere tilgjengelig (klar, under avklaring, nei, na): 

---
### Estimat
Grov, ved innleggelse i produktkø, dv ( 60-31, 30-11,10-3, >3): 
Estimat (sprint til akseptansetest): dv

---
### Forslag nye brukerhistorier (scenarie 1):

---
### Åpne punkter - lukkes før sprint

---
### Annet

---

**Comment by TageGitHub** [comment]
Voidereføres i #172

**Comment by TageGitHub** [comment]
Oppdateres ihht dagens forståelse.

**Comment by lillelars** [comment]
@tblix @benedicteos Hva er status for denne? Har vi falt ned på alternativ 1?

**Comment by lillelars** [comment]
Håndteres i #387

**Comment by TageGitHub** [comment]
håndteres av #272
