### ISSUE TITLE
Arving signerer for å påta seg ansvar for avdødes gjeld og andre forpliktelser

### ISSUE THREAD

**Issue by curlingnina** [Altinn/oed#28]
**Brukerhistorie:**
Som en arving
ønsker jeg å signere for å påta meg ansvar for avdødes gjeld og andre forpliktelser
slik at jeg får sendt inn erklæring om privat skifte til tingretten.

#### Forretningsverdi 1 (1-5, der 1 er mest kritisk/viktig og 5 er nice-to-have):

Lenke til trådskisser:
Lenke til design: 
Lenke til arkitektur:

**Godkjent Juridisk (OK // N/A // Ikke godkjent)**
Ikke godkjent

#### Akseptansekriterier (minimum happy-case):
- Jeg får informasjon om hva det innebærer å påta seg ansvar for avdødes gjeld og andre forpliktelser
- Jeg kan velge å signere for å påta meg ansvar for avdødes gjeld og andre forpliktelser
- Jeg kan velge å signere for å ikke påta meg ansvar for avdødes gjeld og andre forpliktelser

#### TODO:
- [ ] Hva skal skje/hva skal arving se dersom han velger å påta seg ansvar for avdødes forpliktelser?
- [ ] Hva skal skje/hva skal arving se dersom han velger å ikke påta seg ansvar for avdødes forpliktelser etc.?
- [ ] Hvis arving signerer for å ikke påta seg ansvar for avdødes gjeld og andre forpliktelser, skal ikke erklæring om privat skifte sendes til tingretten. Hva skal da skje? (Denne brukerhistorien passer egentlig ikke scenario 1 med kun en arving)
- [ ] Skal tingretten ha informasjon om at arving aktivt har valgt å signere for å ikke påta seg ansvar for avdødes gjeld og andre forpliktelser?
- [ ] Gjør om denne brukerhistorien til to: signering for og signering for ikke

Forbehold/avklaringer:
- JÅB: Altinns standard signeringsløsning brukes. Ikke klar i T3.0 pr august 2020.
- For scenario 1: arving må påta seg ansvar for avdødes gjeld og andre forpliktelser 

**SCENARIO X:**
- Erklæring om privat skifte kan ikke sendes inn før alle arvinger har aktivt signert for å påta seg eller ikke påta seg ansvar for avdødes gjeld og andre forpliktelser.

#### Scenario:
Tittel:
Gitt at...
og...
når..
så...

**Comment by TageGitHub** [comment]
Videreføres av#224 #225 #226 #228
